sudo: required

language: java

jdk:
  - openjdk6

os:
  - linux

before_cache:
  - chmod +x gradlew
  - ./gradlew clean
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    
before_install:
 - chmod +x gradlew
 - ./gradlew clean

script:
  - ./gradlew build
