sudo: required

language: java

jdk:
  - openjdk6

os:
  - linux

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
 - curl -H 'Cache-Control: no-cache' -s https://raw.githubusercontent.com/tamutamu-gradle-org/prep_travis/master/prepare.sh | sudo /bin/bash
 - chmod +x gradlew
 - ls -l /home/travis/.m2/repository/com/nablarch/framework/nablarch-core-applog/

script:
  - ./gradlew build
