sudo: required

service: docker

language: java

jdk:
  - openjdk6

os:
  - linux

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
 - "curl -H 'Cache-Control: no-cache' -s https://raw.githubusercontent.com/tamutamu-gradle-org/prep_travis/master/prepare.sh | /bin/bash"
 - chmod +x gradlew

script:
  - ./gradlew build
